EXPERIMENT_NAME = "state_v2"

STATE_SIZE = 22
HIDDEN_SIZE = 256

LEARNING_RATE = 0.001
GAMMA = 0.9

MAX_MEMORY = 100_000
BATCH_SIZE = 1000

EPSILON_START = 1.0
EPSILON_MIN = 0.05
EPSILON_DECAY = 0.995

TARGET_UPDATE_FREQUENCY = 100
CHECKPOINT_FREQUENCY = 500

REWARD_FOOD = 10
REWARD_DEATH = -10
REWARD_STEP = 0

SEED = 42

DEFAULT_TRAIN_EPISODES = 200
DEFAULT_EVAL_EPISODES = 100
DEFAULT_RENDER = False
TRAINING_SPEED = 60
DEFAULT_LOG_DIR = f"logs/{EXPERIMENT_NAME}"
DEFAULT_CHECKPOINT_DIR = f"checkpoints/{EXPERIMENT_NAME}"
DEFAULT_DASHBOARD_PATH = f"{DEFAULT_LOG_DIR}/dashboard.png"

DECISION_LOG_EVERY_N_EPISODES = 10
